// GENERATED by packages/schema/export_ts.py — do not edit.
// Source of truth: packages/schema/models.py

export type JobStatus = "queued" | "tts" | "lipsync" | "assemble" | "review" | "publishing" | "published" | "failed" | "cancelled";

export type AssetOrigin = "generated" | "stock" | "own";

export type GenerationKind = "text_to_video" | "image_to_video" | "video_to_video" | "image" | "upscale" | "music" | "talking_image" | "voice";

export type GenerationStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";

export type VideoFormat = "long" | "short";

export type IdentityTrainingStatus = "untrained" | "queued" | "training" | "trained" | "failed";

export type ProjectKind = "video" | "movie" | "game" | "other";

export interface WatermarkConfig {
  text?: string;
  position?: "bottom_right";
  persistent?: boolean;
}

export interface PublishConfig {
  altered_content?: boolean;
  visibility?: "private";
}

export interface VoiceProfileCreate {
  name: string;
  engine?: string;
  version?: number;
  reference_audio_uri: string;
  embedding_uri?: string | null;
}

export interface VoiceProfileRead {
  name: string;
  engine?: string;
  version?: number;
  reference_audio_uri: string;
  embedding_uri?: string | null;
  id: string;
  created_at: string;
}

export interface BaseLoopCreate {
  name: string;
  source_uri: string;
  latents_uri?: string | null;
  bbox_uri?: string | null;
  fps: number;
  frame_count: number;
  seam_index?: number | null;
}

export interface BaseLoopRead {
  name: string;
  source_uri: string;
  latents_uri?: string | null;
  bbox_uri?: string | null;
  fps: number;
  frame_count: number;
  seam_index?: number | null;
  id: string;
  vfr_ratio?: number | null;
  seam_score?: number | null;
  ping_pong?: boolean;
  error?: string | null;
  created_at: string;
}

export interface SegmentRead {
  idx: number;
  text: string;
  pause_after_ms?: number;
  audio_uri?: string | null;
  duration_ms?: number | null;
  seed?: number | null;
  emotion?: string | null;
  id: string;
  job_id: string;
}

export interface RenderJobCreate {
  title: string;
  script: string;
  voice_profile_id: string;
  base_loop_id: string;
  watermark?: WatermarkConfig;
  publish?: PublishConfig;
}

export interface RenderJobRead {
  title: string;
  script: string;
  voice_profile_id: string;
  base_loop_id: string;
  id: string;
  status: JobStatus;
  watermark: WatermarkConfig;
  publish: PublishConfig;
  error?: string | null;
  output_uri?: string | null;
  created_at: string;
  updated_at: string;
  segments?: SegmentRead[];
}

export interface PublishRecordCreate {
  altered_content?: boolean;
  reviewed_by: string;
}

export interface PublishRecordRead {
  altered_content?: boolean;
  reviewed_by: string;
  id: string;
  job_id?: string | null;
  asset_id?: string | null;
  youtube_id?: string | null;
  published_at?: string | null;
  created_at: string;
}

export interface AssetCreate {
  origin: AssetOrigin;
  uri: string;
  caption?: string | null;
  duration_ms?: number | null;
  has_identifiable_people?: boolean;
  license?: string | null;
  source_url?: string | null;
  approved?: boolean;
}

export interface AssetRead {
  origin: AssetOrigin;
  uri: string;
  caption?: string | null;
  duration_ms?: number | null;
  has_identifiable_people?: boolean;
  license?: string | null;
  source_url?: string | null;
  approved?: boolean;
  id: string;
  created_at: string;
}

export interface GenerationTarget {
  provider: string;
  model: string;
}

export interface GenerationCreate {
  provider: string;
  model: string;
  kind: GenerationKind;
  prompt: string;
  params?: Record<string, unknown> | null;
  fallback?: GenerationTarget[];
  project_id?: string | null;
  identity_id?: string | null;
  enhance?: boolean;
}

export interface GenerationRead {
  provider: string;
  model: string;
  kind: GenerationKind;
  prompt: string;
  id: string;
  status: GenerationStatus;
  params?: Record<string, unknown> | null;
  fallback?: Record<string, unknown>[] | null;
  external_id?: string | null;
  cost?: number | null;
  error?: string | null;
  asset_id?: string | null;
  project_id?: string | null;
  identity_id?: string | null;
  source_asset_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface LoraRef {
  name: string;
  weights_uri: string;
  license: string;
  license_audited?: boolean;
}

export interface CameraPresetRead {
  id: string;
  label: string;
  description: string;
  category: string;
  motion_code: string;
  prompt_template: string;
  stackable?: boolean;
  loras?: LoraRef[];
}

export interface StyleTemplateRead {
  id: string;
  label: string;
  description: string;
  prompt_suffix: string;
  params?: Record<string, unknown>;
}

export interface EffectPresetRead {
  id: string;
  label: string;
  description: string;
  category: string;
  prompt_template: string;
  stackable?: boolean;
}

export interface IdentityCreate {
  name: string;
  description?: string | null;
  reference_asset_ids?: string[];
}

export interface IdentityRead {
  name: string;
  description?: string | null;
  id: string;
  reference_asset_ids?: string[];
  consent_recorded_by?: string | null;
  consent_at?: string | null;
  consent_note?: string | null;
  has_consent?: boolean;
  training_status: IdentityTrainingStatus;
  lora_uri?: string | null;
  error?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConsentRecord {
  recorded_by: string;
  note?: string | null;
}

export interface ShotCreate {
  idx: number;
  subject: string;
  preset_ids?: string[];
  duration_target_ms?: number;
  notes?: string | null;
  asset_id?: string | null;
}

export interface ShotRead {
  idx: number;
  subject: string;
  preset_ids?: string[];
  duration_target_ms?: number;
  notes?: string | null;
  id: string;
  storyboard_id: string;
  generation_id?: string | null;
  asset_id?: string | null;
  generation_status?: GenerationStatus | null;
}

export interface StoryboardCreate {
  title: string;
  format?: VideoFormat;
  style_id?: string | null;
  project_id?: string | null;
}

export interface StoryboardRead {
  title: string;
  format?: VideoFormat;
  style_id?: string | null;
  project_id?: string | null;
  id: string;
  created_at: string;
  updated_at: string;
  shots?: ShotRead[];
}

export interface ProjectCreate {
  title: string;
  description?: string | null;
  kind?: ProjectKind;
}

export interface ProjectRead {
  title: string;
  description?: string | null;
  kind?: ProjectKind;
  id: string;
  created_at: string;
  updated_at: string;
  asset_count?: number;
  storyboard_count?: number;
}

export interface TimelineClip {
  id: string;
  asset_id: string;
  start_ms: number;
  in_ms?: number;
  out_ms: number;
}

export interface AudioClip {
  id: string;
  asset_id: string;
  start_ms: number;
  in_ms?: number;
  out_ms: number;
  gain?: number;
  duck?: boolean;
  fade_in_ms?: number;
  fade_out_ms?: number;
}

export interface TextClip {
  id: string;
  text: string;
  start_ms: number;
  end_ms: number;
  y_pct?: number;
}

export interface TimelineDocument {
  format?: VideoFormat;
  transition_ms?: number;
  video_tracks?: TimelineClip[][];
  audio_tracks?: AudioClip[][];
  texts?: TextClip[];
}

export interface TimelineDocCreate {
  title: string;
  storyboard_id?: string | null;
  project_id?: string | null;
  doc?: TimelineDocument;
}

export interface TimelineDocRead {
  title: string;
  storyboard_id?: string | null;
  project_id?: string | null;
  id: string;
  version: number;
  doc: TimelineDocument;
  created_at: string;
  updated_at: string;
}

export interface TimelineDocSave {
  doc: TimelineDocument;
  base_version: number;
}

export interface RentalProviderStatus {
  name: string;
  label: string;
  configured: boolean;
  online?: boolean;
  balance_usd?: number | null;
  running_instances?: number | null;
  burn_usd_per_hr?: number | null;
  note?: string | null;
}
