// GENERATED by packages/schema/export_ts.py — do not edit.
// Source of truth: packages/schema/models.py

export type JobStatus = "queued" | "tts" | "lipsync" | "assemble" | "review" | "publishing" | "published" | "failed" | "cancelled";

export type AssetOrigin = "generated" | "stock" | "own";

export type GenerationKind = "text_to_video" | "image_to_video" | "image" | "upscale";

export type GenerationStatus = "queued" | "running" | "succeeded" | "failed";

export interface WatermarkConfig {
  text?: string;
  position?: "bottom_right";
  persistent?: boolean;
}

export interface PublishConfig {
  altered_content?: boolean;
  visibility?: "private";
}

export interface VoiceProfileCreate {
  name: string;
  engine?: string;
  version?: number;
  reference_audio_uri: string;
  embedding_uri?: string | null;
}

export interface VoiceProfileRead {
  name: string;
  engine?: string;
  version?: number;
  reference_audio_uri: string;
  embedding_uri?: string | null;
  id: string;
  created_at: string;
}

export interface BaseLoopCreate {
  name: string;
  source_uri: string;
  latents_uri?: string | null;
  bbox_uri?: string | null;
  fps: number;
  frame_count: number;
  seam_index?: number | null;
}

export interface BaseLoopRead {
  name: string;
  source_uri: string;
  latents_uri?: string | null;
  bbox_uri?: string | null;
  fps: number;
  frame_count: number;
  seam_index?: number | null;
  id: string;
  created_at: string;
}

export interface SegmentRead {
  idx: number;
  text: string;
  pause_after_ms?: number;
  audio_uri?: string | null;
  duration_ms?: number | null;
  seed?: number | null;
  id: string;
  job_id: string;
}

export interface RenderJobCreate {
  title: string;
  script: string;
  voice_profile_id: string;
  base_loop_id: string;
  watermark?: WatermarkConfig;
  publish?: PublishConfig;
}

export interface RenderJobRead {
  title: string;
  script: string;
  voice_profile_id: string;
  base_loop_id: string;
  id: string;
  status: JobStatus;
  watermark: WatermarkConfig;
  publish: PublishConfig;
  error?: string | null;
  created_at: string;
  updated_at: string;
  segments?: SegmentRead[];
}

export interface PublishRecordCreate {
  altered_content?: boolean;
  reviewed_by: string;
}

export interface PublishRecordRead {
  altered_content?: boolean;
  reviewed_by: string;
  id: string;
  job_id: string;
  youtube_id?: string | null;
  published_at?: string | null;
  created_at: string;
}

export interface AssetCreate {
  origin: AssetOrigin;
  uri: string;
  caption?: string | null;
  duration_ms?: number | null;
  has_identifiable_people?: boolean;
  license?: string | null;
  source_url?: string | null;
  approved?: boolean;
}

export interface AssetRead {
  origin: AssetOrigin;
  uri: string;
  caption?: string | null;
  duration_ms?: number | null;
  has_identifiable_people?: boolean;
  license?: string | null;
  source_url?: string | null;
  approved?: boolean;
  id: string;
  created_at: string;
}

export interface GenerationTarget {
  provider: string;
  model: string;
}

export interface GenerationCreate {
  provider: string;
  model: string;
  kind: GenerationKind;
  prompt: string;
  params?: Record<string, unknown> | null;
  fallback?: GenerationTarget[];
}

export interface GenerationRead {
  provider: string;
  model: string;
  kind: GenerationKind;
  prompt: string;
  id: string;
  status: GenerationStatus;
  params?: Record<string, unknown> | null;
  fallback?: Record<string, unknown>[] | null;
  external_id?: string | null;
  cost?: number | null;
  error?: string | null;
  asset_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface LoraRef {
  name: string;
  weights_uri: string;
  license: string;
  license_audited?: boolean;
}

export interface CameraPresetRead {
  id: string;
  label: string;
  description: string;
  category: string;
  motion_code: string;
  prompt_template: string;
  stackable?: boolean;
  loras?: LoraRef[];
}
