"""Generate web/src/types/schema.ts from the Pydantic models.

Deterministic by construction: model order comes from the EXPORTED_* lists,
field order from definition order, no timestamps, LF endings. CI re-runs this
and fails on any diff — a schema change that isn't re-exported cannot merge.

Run after ANY schema change:  python packages/schema/export_ts.py
"""

from __future__ import annotations

import sys
import types
import typing
import uuid
from datetime import date, datetime
from enum import Enum
from pathlib import Path

from pydantic import BaseModel
from pydantic_core import PydanticUndefined

from schema.models import EXPORTED_ENUMS, EXPORTED_MODELS

BANNER = (
    "// GENERATED by packages/schema/export_ts.py — do not edit.\n"
    "// Source of truth: packages/schema/models.py\n"
)

_PRIMITIVES: dict[type, str] = {
    str: "string",
    uuid.UUID: "string",
    datetime: "string",
    date: "string",
    int: "number",
    float: "number",
    bool: "boolean",
}


def ts_type(annotation: object) -> str:
    if annotation is type(None):
        return "null"
    if annotation in _PRIMITIVES:
        return _PRIMITIVES[annotation]  # type: ignore[index]

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin in (typing.Union, types.UnionType):
        return " | ".join(ts_type(a) for a in args)
    if origin is typing.Literal:
        return " | ".join(f'"{a}"' if isinstance(a, str) else str(a).lower() for a in args)
    if origin in (list, tuple, set):
        inner = ts_type(args[0]) if args else "unknown"
        return f"{inner}[]"
    if origin is dict:
        value = ts_type(args[1]) if len(args) == 2 else "unknown"
        return f"Record<string, {value}>"

    if isinstance(annotation, type):
        if issubclass(annotation, Enum):
            return annotation.__name__
        if issubclass(annotation, BaseModel):
            return annotation.__name__

    raise TypeError(f"export_ts: no TS mapping for annotation {annotation!r}")


def _emit_enum(enum_cls: type[Enum]) -> str:
    values = " | ".join(f'"{member.value}"' for member in enum_cls)
    return f"export type {enum_cls.__name__} = {values};\n"


def _emit_model(model_cls: type[BaseModel]) -> str:
    lines = [f"export interface {model_cls.__name__} {{"]
    for name, field in model_cls.model_fields.items():
        optional = field.default is not PydanticUndefined or field.default_factory is not None
        marker = "?" if optional else ""
        lines.append(f"  {name}{marker}: {ts_type(field.annotation)};")
    lines.append("}\n")
    return "\n".join(lines)


def generate() -> str:
    parts = [BANNER]
    for enum_cls in EXPORTED_ENUMS:
        parts.append(_emit_enum(enum_cls))
    for model_cls in EXPORTED_MODELS:
        parts.append(_emit_model(model_cls))
    return "\n".join(parts)


def main() -> int:
    out_path = Path(__file__).resolve().parents[2] / "web" / "src" / "types" / "schema.ts"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generate(), encoding="utf-8", newline="\n")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
